/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPrincipal;
import Controlador.ControladorProducto;
import Modelo.CRUDPedido;
import Modelo.Pedido;
import javax.swing.JOptionPane;

/**
 *
 * @author PC_INGLS632
 */
public class VLogin extends javax.swing.JFrame {

    /**
     * Creates new form VLogin
     */
    public VLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_rol_nuevo = new javax.swing.JLabel();
        txt_nombre_nuevo = new javax.swing.JTextField();
        label_contrasenia = new javax.swing.JLabel();
        txt_clave_nueva = new javax.swing.JPasswordField();
        btn_crear_user = new javax.swing.JButton();
        btn_iniciar_sesion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        label_usuario = new javax.swing.JLabel();
        label_nombre_nuevo = new javax.swing.JLabel();
        label_apellido_nuevo = new javax.swing.JLabel();
        label_usuario_nuevo = new javax.swing.JLabel();
        label_clave_nueva = new javax.swing.JLabel();
        txt_apellido_nuevo = new javax.swing.JTextField();
        txt_usuario_nuevo = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_contrasenia = new javax.swing.JPasswordField();
        combo_roles = new javax.swing.JComboBox<>();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_rol_nuevo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label_rol_nuevo.setText("Rol");
        getContentPane().add(label_rol_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        txt_nombre_nuevo.setBackground(new java.awt.Color(204, 204, 204));
        txt_nombre_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 180, 30));

        label_contrasenia.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label_contrasenia.setText("Contraseña:");
        getContentPane().add(label_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        txt_clave_nueva.setBackground(new java.awt.Color(204, 204, 204));
        txt_clave_nueva.setText("");
        txt_clave_nueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_clave_nuevaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_clave_nueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 180, 30));

        btn_crear_user.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_crear_user.setText("Crear Usuario");
        btn_crear_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crear_userActionPerformed(evt);
            }
        });
        getContentPane().add(btn_crear_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, -1));

        btn_iniciar_sesion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_iniciar_sesion.setText("Iniciar Sesión");
        btn_iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciar_sesionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        label_usuario.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label_usuario.setText("Usuario:");
        getContentPane().add(label_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        label_nombre_nuevo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label_nombre_nuevo.setText("Nombre");
        getContentPane().add(label_nombre_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        label_apellido_nuevo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label_apellido_nuevo.setText("Apellido");
        getContentPane().add(label_apellido_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        label_usuario_nuevo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label_usuario_nuevo.setText("Usuario");
        getContentPane().add(label_usuario_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        label_clave_nueva.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label_clave_nueva.setText("Clave");
        getContentPane().add(label_clave_nueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        txt_apellido_nuevo.setBackground(new java.awt.Color(204, 204, 204));
        txt_apellido_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellido_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_apellido_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 180, 30));

        txt_usuario_nuevo.setBackground(new java.awt.Color(204, 204, 204));
        txt_usuario_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuario_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usuario_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 180, 30));

        txt_nombre.setBackground(new java.awt.Color(204, 204, 204));
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 180, 30));

        txt_contrasenia.setBackground(new java.awt.Color(204, 204, 204));
        txt_contrasenia.setText("");
        txt_contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraseniaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 180, 30));

        combo_roles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "USER"}));
        combo_roles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_rolesActionPerformed(evt);
            }
        });
        getContentPane().add(combo_roles, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombre_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_nuevoActionPerformed

    private void btn_crear_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crear_userActionPerformed

//        if (txt_clave_nueva.getText().equalsIgnoreCase(txt_nombre_nuevo.getText())) {
//            Pedido pro = new Pedido();
//            CRUDPedido proC = new CRUDPedido();
//            VProducto frmPro = new VProducto();
//            ControladorProducto ctrlPro = new ControladorProducto(pro, frmPro, proC);
//            VPrincipal frmPri = new VPrincipal();
//            ControladorPrincipal ctrlPri = new ControladorPrincipal(frmPri, frmPro);
//            ctrlPri.inciar();
//            frmPri.setVisible(true);
//            this.dispose();
//
//        } else {
//            JOptionPane.showMessageDialog(null, "Usuario o Contraseña incorrectas");
//        }
    }//GEN-LAST:event_btn_crear_userActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_clave_nuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_clave_nuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_clave_nuevaActionPerformed

    private void btn_iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciar_sesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_iniciar_sesionActionPerformed

    private void txt_apellido_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellido_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellido_nuevoActionPerformed

    private void txt_usuario_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuario_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuario_nuevoActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_contraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraseniaActionPerformed

    private void combo_rolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_rolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_rolesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_crear_user;
    public javax.swing.JButton btn_iniciar_sesion;
    public javax.swing.JComboBox<String> combo_roles;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel label_apellido_nuevo;
    public javax.swing.JLabel label_clave_nueva;
    public javax.swing.JLabel label_contrasenia;
    public javax.swing.JLabel label_nombre_nuevo;
    public javax.swing.JLabel label_rol_nuevo;
    public javax.swing.JLabel label_usuario;
    public javax.swing.JLabel label_usuario_nuevo;
    public javax.swing.JTextField txt_apellido_nuevo;
    public javax.swing.JPasswordField txt_clave_nueva;
    public javax.swing.JPasswordField txt_contrasenia;
    public javax.swing.JTextField txt_nombre;
    public javax.swing.JTextField txt_nombre_nuevo;
    public javax.swing.JTextField txt_usuario_nuevo;
    // End of variables declaration//GEN-END:variables
}
